apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kari-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: student-5
    syncPolicy:
      automated: {}
    sources:
      - repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.4.0
        helm:
          valueFiles:
            - $values/jenkins/values.yaml
        chart: jenkins
      - repoURL: https://github.com/kahe-devops/argocd-katas
        targetRevision: main
        ref: values
